#!/usr/bin/env python3
"""gen_unicode_tables.py — emit include/unicode_cat.h for the C++ tokenizer's pre-tokenizer.

DeepSeek's pre-tokenizer regex uses the unicode general categories \\p{L}, \\p{M}, \\p{N},
\\p{P} and \\p{S}. std::regex has no idea what those are, and vendoring a full unicode engine
to answer five yes/no questions would be absurd. So we bake the answers: walk every codepoint
once, HERE, offline, and emit sorted [lo,hi] range tables that the tokenizer binary-searches.

This is codegen, not runtime — "no Python on the hot path" is about serving, and the generated
header has no dependency on this script. Regenerate only if the Python unicodedata version moves,
and re-run tests/gate_tokenizer.cpp afterwards (it compares against HF, which uses its own tables;
a mismatch would show up there as a split difference).
"""
import sys, unicodedata

MAX = 0x110000
# The five classes the pre-tokenizer actually asks about. `Z` (separators) is NOT one of them:
# the regex spells whitespace as \s, which is an ASCII-plus-a-few-fixed-codepoints set, not a
# general category — see is_space() in the header.
WANT = {'L': 'L', 'M': 'M', 'N': 'N', 'P': 'P', 'S': 'S'}


def ranges_for(prefix):
    out, lo, prev = [], None, None
    for cp in range(MAX):
        c = unicodedata.category(chr(cp))
        hit = c[0] == prefix
        if hit and lo is None:
            lo = cp
        elif not hit and lo is not None:
            out.append((lo, prev))
            lo = None
        if hit:
            prev = cp
    if lo is not None:
        out.append((lo, MAX - 1))
    return out


def emit(f, name, rs):
    f.write(f'static const uint32_t UC_{name}[][2] = {{\n')
    for i, (a, b) in enumerate(rs):
        f.write(f'{{0x{a:X},0x{b:X}}},')
        if i % 8 == 7:
            f.write('\n')
    f.write(f'\n}};\nstatic const int UC_{name}_N = {len(rs)};\n\n')


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else 'include/unicode_cat.h'
    tables = {k: ranges_for(v) for k, v in WANT.items()}
    with open(path, 'w') as f:
        f.write('// unicode_cat.h — GENERATED by tools/gen_unicode_tables.py. Do not edit.\n')
        f.write(f'// unicodedata {unicodedata.unidata_version}, python {sys.version.split()[0]}\n')
        f.write('// Sorted, disjoint [lo,hi] ranges per unicode general-category major class.\n')
        f.write('#pragma once\n#include <cstdint>\n\n')
        for k in 'LMNPS':
            emit(f, k, tables[k])
        f.write('''static inline bool uc_in(const uint32_t (*t)[2], int n, uint32_t c) {
    int lo = 0, hi = n - 1;
    while (lo <= hi) { int m = (lo + hi) >> 1;
        if (c < t[m][0]) hi = m - 1; else if (c > t[m][1]) lo = m + 1; else return true; }
    return false;
}
static inline bool uc_is_L(uint32_t c){ return uc_in(UC_L, UC_L_N, c); }
static inline bool uc_is_M(uint32_t c){ return uc_in(UC_M, UC_M_N, c); }
static inline bool uc_is_N(uint32_t c){ return uc_in(UC_N, UC_N_N, c); }
static inline bool uc_is_P(uint32_t c){ return uc_in(UC_P, UC_P_N, c); }
static inline bool uc_is_S(uint32_t c){ return uc_in(UC_S, UC_S_N, c); }
''')
    tot = sum(len(v) for v in tables.values())
    print(f'wrote {path}: ' + ', '.join(f'{k}={len(tables[k])}' for k in 'LMNPS') + f' ({tot} ranges)')


if __name__ == '__main__':
    main()
