#!/usr/bin/env python3
"""runs_index.py — regenerate RUNS.md, one row per training run and measurement, from the evidence.

WHY GENERATED AND NOT HAND-WRITTEN. A hand-maintained index drifts from the logs the moment a run is
added, and an index that disagrees with the evidence is worse than none: it invites conclusions the
data does not support. This reads `evidence/` and `~/model-backups/heads/` and writes what is
actually there, so a stale row is impossible — a run that vanished from the evidence vanishes from
the index.

It answers one question directly: for every fine-tune run, where is the training log, where is the
eval that measured it, where are the trained weights, and what did it score.

  python3 tools/runs_index.py [--out RUNS.md]
"""
import argparse, csv, glob, json, os, re, statistics as st, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STORE = os.path.expanduser("~/model-backups/heads")
RELEASES = os.path.expanduser("~/model-backups/releases")
sys.path.insert(0, os.path.join(ROOT, "tools"))
from holdout_rate import rate as pooled_rate                            # noqa: E402


def ev(*p):
    return os.path.join(ROOT, "evidence", *p)


def exists(p):
    return os.path.exists(p) and os.path.getsize(p) > 0


def link(p):
    return f"[`{os.path.basename(p)}`](evidence/{os.path.basename(p)})" if exists(p) else "—"


def train_summary(path):
    if not exists(path):
        return None
    first = last = None
    n = 0
    for l in open(path, errors="ignore"):
        m = re.match(r"\[train\] step (\d+):.*loss=([\d.]+)", l)
        if m:
            n += 1
            v = float(m.group(2))
            first = v if first is None else first
            last = v
    return None if not n else {"steps": n, "first": first, "last": last}


def sessions():
    out = []
    for name in sorted(glob.glob(os.path.join(STORE, "*"))):
        pass
    for name in ("s1", "s2", "s3"):
        log = ev(f"{name}_session.log")
        if not exists(log):
            continue
        txt = open(log, errors="ignore").read()
        verdict = re.findall(r"VERDICT: (\w+)", txt)
        promoted = "PROMOTED" if "] PROMOTED" in txt else (
            "archived (not promoted)" if "not promoted" in txt else "in flight")
        gate = re.search(r"gate OK \(([\d.]+)%\)", txt)
        ntrain = re.search(r"hold-out: (\d+) sequence\(s\) reserved, (\d+) for training", txt)
        r = pooled_rate(ev(f"{name}_eval.log")) if exists(ev(f"{name}_eval.log")) else None
        out.append({"name": name, "train": ntrain.group(2) if ntrain else "—",
                    "hold": ntrain.group(1) if ntrain else "—",
                    "gate": gate.group(1) + " %" if gate else "—",
                    "verdict": verdict[-1] if verdict else ("in flight" if "pass 1" in txt else "—"),
                    "status": promoted,
                    "rate": f"{r['tok_s_pooled']:.2f}" if r else "—",
                    "logs": [ev(f"{name}_session.log"), ev(f"{name}_c0_train.log"),
                             ev(f"{name}_eval.log")],
                    "tm": train_summary(ev(f"{name}_c0_train.log"))})
    return out


def arms():
    out = []
    for f in sorted(glob.glob(ev("*_abl_*_eval.log"))):
        m = re.search(r"(\w+)_abl_ce([\d.]+)_tv([\d.]+)_eval", os.path.basename(f))
        if not m:
            continue
        r = pooled_rate(f)
        out.append({"session": m.group(1), "ce": m.group(2), "tv": m.group(3),
                    "rate": f"{r['tok_s_pooled']:.2f}" if r else "—", "eval": f,
                    "train": ev(f"{m.group(1)}_abl_ce{m.group(2)}_tv{m.group(3)}_train.log")})
    return out


def sweeps():
    out = []
    for csvf in sorted(glob.glob(ev("*_measurements.csv"))):
        rows = []
        with open(csvf) as fh:
            for r in csv.DictReader(fh):
                try:
                    rows.append((r["threshold"], float(r["tok_s"])))
                except (ValueError, KeyError):
                    pass
        if not rows:
            continue
        lv = sorted({t for t, _ in rows})
        best = max(lv, key=lambda t: st.mean([v for k, v in rows if k == t]))
        out.append({"file": csvf, "n": len(rows), "levels": len(lv),
                    "reps": len(rows) // max(1, len(lv)),
                    "best": best,
                    "best_mean": f"{st.mean([v for k, v in rows if k == best]):.2f}"})
    return out


HEADER = """# RUNS — every fine-tune run and measurement, with its evidence

Generated by `tools/runs_index.py` from `evidence/` and `~/model-backups/`. Do not edit by hand: a
hand-maintained index drifts from the logs, and an index that disagrees with the evidence invites
conclusions the data does not support.

**What is in git and what is not.** Every log, measurement CSV and metrics file referenced here is
committed. The **weights are not** — they are 1 GB (trained tensors) to 7 GB (materialised head)
each, and they live in `~/model-backups/heads/<name>/` with a sha256 per file plus a `head_card.json`
recording the engine revision they were measured at. `HEAD_REGISTRY.md` is the promotion record,
rejects included. That split is deliberate: the engine and its evidence are in git and therefore
safe; the weights are the one product that git cannot hold, which is what the backup store and the
checksums are for.

"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(ROOT, "RUNS.md"))
    a = ap.parse_args()
    L = [HEADER]

    L.append("## Fine-tune sessions\n")
    L.append("| session | train seqs | hold-out | port/engine gate | suite tok/s | primary verdict | outcome |")
    L.append("|---|---|---|---|---|---|---|")
    for s in sessions():
        L.append(f"| `{s['name']}` | {s['train']} | {s['hold']} | {s['gate']} | {s['rate']} | "
                 f"{s['verdict']} | {s['status']} |")
    L.append("")
    L.append("Per-session evidence:\n")
    for s in sessions():
        parts = " · ".join(link(p) for p in s["logs"])
        tm = s["tm"]
        tms = (f" — training: {tm['steps']} steps, loss {tm['first']:.4f} → {tm['last']:.4f}"
               if tm else "")
        L.append(f"- **`{s['name']}`**: {parts}{tms}")
    L.append("")

    ar = arms()
    if ar:
        L.append("## CE/TV objective ablation (F112 → F119)\n")
        L.append("Each arm retrained on the **same** capture, measured on the **same** frozen suite "
                 "at the same adaptK — one variable.\n")
        L.append("| arm | a_ce | a_tv | suite tok/s | evidence |")
        L.append("|---|---|---|---|---|")
        for x in ar:
            L.append(f"| `{x['session']}-abl-ce{x['ce']}_tv{x['tv']}` | {x['ce']} | {x['tv']} | "
                     f"{x['rate']} | {link(x['eval'])} · {link(x['train'])} |")
        L.append("")

    sw = sweeps()
    if sw:
        L.append("## Threshold sweeps and head-offs\n")
        L.append("| measurement set | levels | reps | runs | best level | best mean tok/s |")
        L.append("|---|---|---|---|---|---|")
        for x in sw:
            L.append(f"| `{os.path.basename(x['file'])}` | {x['levels']} | {x['reps']} | {x['n']} | "
                     f"{x['best']} | {x['best_mean']} |")
        L.append("\nEach CSV carries the per-run index, which `tools/sweep_analyze.py` fits as a "
                 "covariate — on this box a sweep run in parameter order confounds the parameter "
                 "with warm-up drift (F120/F121).\n")

    if os.path.isdir(STORE):
        L.append("## Archived weights\n")
        L.append("| archive | trained tensors | materialised head | card |")
        L.append("|---|---|---|---|")
        for n in sorted(os.listdir(STORE)):
            d = os.path.join(STORE, n)
            if not os.path.isdir(d):
                continue
            tr = "yes" if exists(os.path.join(d, "mtp_trained.safetensors")) else "no"
            hd = "yes" if exists(os.path.join(d, "model.safetensors.index.json")) else "rebuildable"
            L.append(f"| `~/model-backups/heads/{n}` | {tr} | {hd} | "
                     f"{'yes' if exists(os.path.join(d,'head_card.json')) else 'no'} |")
        L.append("")

    if os.path.isdir(RELEASES):
        L.append("## Packaged releases\n")
        for n in sorted(os.listdir(RELEASES)):
            d = os.path.join(RELEASES, n)
            if os.path.isdir(d):
                sz = sum(os.path.getsize(os.path.join(d, f)) for f in os.listdir(d)
                         if os.path.isfile(os.path.join(d, f)))
                L.append(f"- `~/model-backups/releases/{n}` — {sz/1e6:.0f} MB, "
                         f"{len(os.listdir(d))} files, checksummed in `SHA256SUMS`")
        L.append("")

    rev = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True,
                         text=True, cwd=ROOT).stdout.strip()
    L.append(f"---\nRegenerate with `python3 tools/runs_index.py`. Engine revision at generation: "
             f"`{rev}`.\n")
    open(a.out, "w").write("\n".join(L))
    print(f"wrote {a.out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
