#!/usr/bin/env python3
"""vocab_rank.py — build and PRICE an FR-Spec draft-vocabulary ranking from the target's own outputs.

F97 killed every id-ordered variant of this lever with a measurement: ByteLevel-BPE ids are not
frequency-ordered for this tokenizer, the most frequent tokens above id 32000 carry 11.25 % of all
tokens, and a coverage miss costs an entire accepted run. It also said what would revive the lever:
a frequency ranking fitted to a corpus **representative of serving traffic** — which is exactly what
S5's capture produces as a by-product, since the responses are regenerated by the target itself.

THE ONE DISCIPLINE THIS TOOL EXISTS TO ENFORCE. A ranking fitted and evaluated on the same corpus
reports ~100 % coverage **by construction** — every token it saw is in the list. F97 already caught
that shape once (100 % at K=16000 on 1.5 MB of our own markdown and CUDA source) and correctly
refused to trust it. So this tool never reports a fitted-set number as the headline:

  * the ranking is built on a TRAIN split
  * coverage is reported on a HELD-OUT split the ranking has never seen
  * the gap between the two is printed, because that gap IS the overfit

A held-out coverage of 99.9 % means something. A fitted coverage of 100 % means nothing.

  python3 tools/vocab_rank.py --gen <gen.txt> [--prompts <seed file>] [--holdout 0.2] [--out rank.json]
"""
import argparse, json, os, random, sys
from collections import Counter

# Priced from F97's measured cycle: the lm_head read is 24.8 % of a 129280-vocab read at K=32000,
# and trimming to K saves proportionally. 4.74 ms at K=32000 => 4.74 / (1 - 32000/129280) ms per
# unit of trimmed fraction, i.e. the full read is worth ~6.31 ms of a 69.5 ms step.
LM_HEAD_MS_FULL = 6.31
CYCLE_MS = 69.5
VOCAB = 129280


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gen", required=True, help="gen.txt: one comma-separated id sequence per line")
    ap.add_argument("--prompts", default=None,
                    help="seed prompt file; its ids are STRIPPED so only the target's own "
                         "generated tokens are counted (a prompt token is not something the "
                         "drafter has to predict)")
    ap.add_argument("--holdout", type=float, default=0.2, help="fraction of SEQUENCES held out")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--ks", default="8000,16000,32000,64000")
    ap.add_argument("--out", default=None)
    ap.add_argument("--curve", action="store_true",
                    help="subsample the train split to measure held-out coverage vs corpus size")
    a = ap.parse_args()

    seqs = [[int(x) for x in l.strip().split(",") if x] for l in open(a.gen) if l.strip()]
    if not seqs:
        sys.exit("no sequences")
    seeds = None
    if a.prompts and os.path.exists(a.prompts):
        seeds = [[int(x) for x in l.strip().split(",") if x] for l in open(a.prompts) if l.strip()]

    gen_only = []
    for i, s in enumerate(seqs):
        if seeds and i < len(seeds) and s[:len(seeds[i])] == seeds[i]:
            gen_only.append(s[len(seeds[i]):])
        else:
            gen_only.append(s[1:] if not seeds else s)          # at minimum drop BOS
    gen_only = [g for g in gen_only if g]

    # SPLIT BY SEQUENCE, not by token. Splitting tokens at random would put a sequence's own
    # vocabulary on both sides and leak the answer -- the held-out set has to be text the ranking
    # has never seen, not a subsample of text it has.
    rng = random.Random(a.seed)
    idx = list(range(len(gen_only)))
    rng.shuffle(idx)
    ncut = max(1, int(len(idx) * a.holdout))
    test_i, train_i = set(idx[:ncut]), idx[ncut:]
    train = [t for i in train_i for t in gen_only[i]]
    test = [t for i in sorted(test_i) for t in gen_only[i]]
    if not train or not test:
        sys.exit(f"split produced empty side: {len(train)} train / {len(test)} test tokens")

    cnt = Counter(train)
    ranked = [t for t, _ in cnt.most_common()]
    print(f"corpus: {len(gen_only)} sequences, {len(train)+len(test)} generated tokens")
    print(f"  train {len(train_i)} seq / {len(train)} tok, {len(cnt)} distinct of {VOCAB}")
    print(f"  test  {len(test_i)} seq / {len(test)} tok, {len(set(test))} distinct  (HELD OUT)")

    test_c = Counter(test)
    n_test = len(test)
    n_train = len(train)
    rows = []
    print(f"\n{'K':>7} {'fitted %':>10} {'HELD-OUT %':>11} {'gap':>7} "
          f"{'saved ms':>9} {'% cycle':>8} {'break-even tau loss':>20}")
    for K in [int(x) for x in a.ks.split(",")]:
        keep = set(ranked[:K])
        fit = 100.0 * sum(c for t, c in cnt.items() if t in keep) / n_train
        hel = 100.0 * sum(c for t, c in test_c.items() if t in keep) / n_test
        saved = LM_HEAD_MS_FULL * (1 - K / VOCAB)
        pct = 100.0 * saved / CYCLE_MS
        # A miss costs the rest of the accepted run. Break-even: the speed gained must exceed the
        # throughput lost to a shorter mean accepted length.
        rows.append({"K": K, "fitted_pct": round(fit, 4), "heldout_pct": round(hel, 4),
                     "saved_ms": round(saved, 3), "pct_cycle": round(pct, 3),
                     "miss_rate_pct": round(100 - hel, 4)})
        print(f"{K:>7} {fit:>9.3f}% {hel:>10.3f}% {fit-hel:>6.3f} "
              f"{saved:>9.2f} {pct:>7.2f}% {pct:>19.2f}%")

    print(f"\nThe last column is the bar: a trim at K is worth taking only if the tau lost to a "
          f"{'{:.3f}'.format(100-rows[-1]['heldout_pct'])}%-scale miss rate costs less than the "
          f"{rows[-1]['pct_cycle']:.2f}% it saves.")
    print("Fitted-vs-held-out gap is the overfit. A fitted 100% with a held-out 97% means the "
          "ranking memorised this corpus and will miss 3% of real traffic (F97).")

    # ---- the curve that actually decides the lever -------------------------------------------
    # Held-out coverage flat across K means the ranking is SHORTER than K: the miss is not "tokens
    # ranked too low", it is "tokens never seen". That is a corpus-size problem, not a K problem,
    # and the only question worth asking is whether it closes as the corpus grows. Subsampling the
    # train split answers it now, from partial data, instead of after the full capture.
    if a.curve:
        print(f"\ncoverage vs TRAIN CORPUS SIZE (held-out set fixed, {len(test)} tokens):")
        print(f"{'train seq':>10} {'train tok':>10} {'distinct':>9} {'held-out %':>11} {'miss %':>8}")
        tr = list(train_i)
        pts = []
        for frac in (0.125, 0.25, 0.5, 1.0):
            k = max(1, int(len(tr) * frac))
            sub = [t for i in tr[:k] for t in gen_only[i]]
            c2 = Counter(sub)
            keep = set(t for t, _ in c2.most_common(max(int(x) for x in a.ks.split(","))))
            hel = 100.0 * sum(c for t, c in test_c.items() if t in keep) / n_test
            pts.append({"train_seq": k, "train_tok": len(sub), "distinct": len(c2),
                        "heldout_pct": round(hel, 4)})
            print(f"{k:>10} {len(sub):>10} {len(c2):>9} {hel:>10.3f}% {100-hel:>7.3f}%")
        # EXTRAPOLATE, don't eyeball. Miss rate decays geometrically per doubling of corpus, so fit
        # log(miss) linearly in log(sequences) and read off the planned session sizes. The lever
        # needs a miss rate small enough that the tau it costs is under the ~4.6 % of cycle it
        # saves; ~0.1 % is the order that clears that.
        if len(pts) >= 3:
            import math
            xs = [math.log2(p["train_seq"]) for p in pts]
            ys = [math.log(max(1e-6, 100 - p["heldout_pct"])) for p in pts]
            n = len(xs); mx = sum(xs) / n; my = sum(ys) / n
            den = sum((x - mx) ** 2 for x in xs)
            b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / den if den else 0.0
            c = my - b * mx
            per_dbl = math.exp(b)
            print(f"\nfit: miss% multiplies by {per_dbl:.3f} per doubling of corpus")
            print(f"{'sequences':>10} {'projected miss %':>18}")
            for nseq in (500, 2000, 5000, 20000, 100000):
                print(f"{nseq:>10} {math.exp(c + b * math.log2(nseq)):>17.3f}%")
            if per_dbl < 1.0:
                need = (math.log(0.1) - c) / b
                print(f"\nreaching 0.1 % miss needs ~2^{need:.1f} = {2**need:.3g} sequences.")
            # ---- price the miss in tau, so the verdict is computed rather than asserted --------
            # First-order model, assumption stated: treat per-position acceptance as independent
            # with probability p, so tau = 1 + sum_{i=1..K} p^i (the 1 is the bonus token, which
            # this project's tau includes). Solve p from the measured baseline, then a draft-vocab
            # miss multiplies per-position acceptance by (1-m): a token the drafter cannot propose
            # ends the run exactly as a rejection does.
            K_BLK, TAU0, TOKS_PER_TAU, BASE_TOKS = 6, 3.5362, 7.664, 22.655

            def tau_of(p):
                return 1.0 + sum(p ** i for i in range(1, K_BLK + 1))

            lo, hi = 0.0, 1.0
            for _ in range(200):
                mid = (lo + hi) / 2
                lo, hi = (mid, hi) if tau_of(mid) < TAU0 else (lo, mid)
            p0 = (lo + hi) / 2
            print(f"\ntau cost of the miss (independent-acceptance model, p0={p0:.4f} "
                  f"reproduces tau {TAU0} at block {K_BLK}):")
            print(f"{'sequences':>10} {'miss %':>8} {'tau':>7} {'tau cost':>9} "
                  f"{'ms saved':>9} {'NET tok/s':>10} {'NET %':>8}")
            best_K = rows[-1]
            for nseq in (500, 2000, 5000, 20000, 100000):
                m = math.exp(c + b * math.log2(nseq)) / 100.0
                tau_m = tau_of(p0 * (1 - m))
                lost = (tau_m - TAU0) * TOKS_PER_TAU
                gained = BASE_TOKS * best_K["pct_cycle"] / 100.0
                net = lost + gained
                print(f"{nseq:>10} {100*m:>7.3f}% {tau_m:>7.3f} {lost:>+9.3f} "
                      f"{gained:>+9.3f} {net:>+10.3f} {100*net/BASE_TOKS:>+7.2f}%")
            print(f"(gain column is K={best_K['K']}, the most conservative trim tested)")
            print("MEASURED ON A PARTIAL, SINGLE-DOMAIN CORPUS -- re-run at the full capture before "
                  "this decides anything. F94 is the precedent for trusting a convenient subset.")

    if a.out:
        json.dump({"source": os.path.abspath(a.gen), "n_sequences": len(gen_only),
                   "n_train_tokens": n_train, "n_test_tokens": n_test,
                   "n_distinct_train": len(cnt), "holdout": a.holdout, "seed": a.seed,
                   "coverage": rows, "ranking_head": ranked[:64],
                   "ranking": ranked}, open(a.out, "w"))
        print(f"\n-> {a.out}  ({len(ranked)} ids, most frequent first)")


if __name__ == "__main__":
    main()
